<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Symfony\Component\HttpFoundation\JsonResponse;

abstract class Request extends FormRequest
{
    public function response(array $errors)
    {
        return new JsonResponse($errors); // TODO: Change the autogenerated stub
    }
}
